services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fxdeal-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/dealsdb
      SPRING_DATASOURCE_USERNAME: dealsuser
      SPRING_DATASOURCE_PASSWORD: dealspassword
      SERVER_PORT: 8080
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    networks:
      - fxdeal-network
    volumes:
      - maven-repo:/root/.m2

  db:
    image: postgres:16-alpine
    container_name: fxdeal-db
    environment:
      POSTGRES_USER: dealsuser
      POSTGRES_PASSWORD: dealspassword
      POSTGRES_DB: dealsdb
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dealsuser -d dealsdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - fxdeal-network

networks:
  fxdeal-network:
    driver: bridge

volumes:
  db_data:
  maven-repo: